#!/bin/bash
# vim:set ts=4 sw=4 syntax=sh:   

N=10000

# generate input file
if [ ! -f b-field.in ]  ; then  
	scc /tmp/sf 'for(; l<'$N'; l++) { for(i=1;i<=10; i++) _ l*10+i," "; __ l; }' > b-field.in
fi

# string-field
scc -x /tmp/sf 'WRL n+=F9; n'
time /tmp/sf  < b-field.in






