#!/bin/bash
# vim:set ts=4 sw=4 syntax=sh:   

sed 's/std:://g' | 
sed 's/sto:://g' | 
sed 's/__gnu_cxx:://g' | 
sed 's/__gnu_debug:://g' | 
sed 's/__debug:://g'  |
sed 's/__cxx1998:://g' | 
sed 's/, allocator<int> //g' 



