#!/bin/bash

[ -f     .scc ]  && .     .scc
[ -f   ~/.scc ]  && .   ~/.scc
[ -f /etc/scc ]  && . /etc/scc

#### get GCC version
: ${GCC_PATH? must be defined}
gcc_ver=${GCC_PATH##*/}

if [[ $gcc_ver =~ ^([[:digit:]])*.([[:digit:]]) ]]  ;   then
	gcc_ver_num=${BASH_REMATCH[1]}${BASH_REMATCH[2]}
fi

#####################################################################################
CXXFLAGS+=" -Wall  -pipe -O0 "
if [[ $gcc_ver_num > 43 ]] ;  then 
	CXXFLAGS+=" -std=gnu++0x "
fi 
[[ $gcc_ver_num < 44 ]] && no_boost=1

FILE=$(find $0  -printf '%l\n')
SCC_HOME="$(dirname ${FILE:-$0})"
CXXFLAGS+=" -I $SCC_HOME "

prg=/tmp/$USER-scc
src=$prg.cc

usage_exit() {
	echo "
	USAGE:  scc [options]  snippets [args] 
		
		-n 	- for each line: read line; split into fields; execute snippet 
		-p 	- for each line: read line; split into fields; execute snippet;  output fields
		-i 	- sets simple (not regex)  IFS (input field separator). Needs boost.  
		-I 	- sets regex IFS. For space separated fields: (\\S+)(\\s+|$) - field data is 1st group; separator is 2nd group 
		-o 	- sets OFS (output field separator) 
		-B	- do not use Boost
		-v 	- vebose
	"
	exit 0
}

####################################################################################### OPTIONS 

[[  $1 ]]  ||  usage_exit

while getopts npvBI:i:o: opt;  do
	case $opt in
		n)	n_opt=1;  is_stream=1;;
		p)	p_opt=1;  is_stream=1;;
		B)	no_boost=1;;
		v)	verbose=1;;
		I)	CXXFLAGS+=" -Darg_IFS=$OPTARG ";; 
		i)	if [[ $OPTARG =~ '"' ]];  then  CXXFLAGS+=" -Darg_ifs=$OPTARG "
			else   				CXXFLAGS+=" -Darg_ifs=\"$OPTARG\" ";  fi;; 
		o)	if [[ $OPTARG =~ '"' ]];  then  CXXFLAGS+=" -Darg_OFS=$OPTARG "
			else   				CXXFLAGS+=" -Darg_OFS=\"$OPTARG\" ";  fi;; 
		?) 	usage_exit;;
	esac
done

[[ $is_stream && $gcc_ver_num < 44   ]]   &&   { echo "scc error: stream ops not supported for older gcc"; exit 1; }

shift $((OPTIND-1))



[[ ! -d /usr/include/boost  ]]  &&  no_boost=1

#####################################################################################  PARSE SNIPPET
#echo -e ' A;\n B; A\n A\n B; A\n {}A\n B({A})\n'|tee /dev/tty|   sed 's/\({[^}]*}\)\{0\}\(\(\((.*)\)\|[^;]\)\+$\)/cout << ( \2 );/'
#echo "$@" | sed 's/\(.*[;}]\)*\([^;}]\+$\)/\1 cout << ( \2 );/' >> $src


end_prt="`echo \"$1\" | sed -n 's/\(.*[;}]\)*\([^;}]\+$\)/1/p'`"

if [[ $verbose ]] ; then 
	echo -n "$1                                 "
	echo -n `(gcc -v  2>&1) | sed -n '/^gcc version/s/^gcc version \([.0-9]*\) .*/\1/p'`
	echo "   no_boost: $no_boost;   n_opt: $n_opt;   p_opt: $p_opt;   is_stream: $is_stream;   end_prt: $end_prt"
	echo "CXXFLAGS:  ${CXXFLAGS}"
fi 

snippet="`echo \"${1%% }\" | sed    's/\(.*[;}]\)*\([^;}]\+$\)/\1 cout << ( \2 );/'`"

[[ $n_opt       && $end_prt ]]	&& snippet+="cout << endl;"
[[ ! $is_stream && $end_prt ]]	&& snippet+="cout << endl;"

shift

#####################################################################################  GENERATE SRC

cat <<  END	 > $src

#include <simple.h>

#ifdef MODERN_GCC 
   #include <scc.h>
#else
   bool read_line() { cerr << "stream operation no supported for old GCC\n";  exit(1);  return false; };
   #define WRL read_line();
#endif

#include <cj.h>
#include <matrix.h>


int main(int argc, char** argv) {
	long i __attribute__((unused)) = 0;
	long j __attribute__((unused)) = 0;
	long k __attribute__((unused)) = 0;
	long n __attribute__((unused)) = 0;

	double x __attribute__((unused)) = 0.0;
	double y __attribute__((unused)) = 0.0;

	std::string s __attribute__((unused));

	{
END

if [[  $is_stream ]];  then 

	echo "	while ( read_line()) { $snippet " >> $src

	if [[  $p_opt ]];  then 

		[[ $end_prt ]]   &&  echo 'cout << OFS;' >> $src

		echo "
			for(int i=0;   i < int(F.size())-1;  i++)
				cout  << F[i] << OFS;
			if (F.size() > 0)  cout << F.back();
			cout << endl;
		" >> $src
	fi

	echo "	}" >> $src

else
	echo "$snippet" >> $src  
fi


echo '	}
}' >>  $src


if [[ $no_boost ]];  then 
	CXXFLAGS+=" -DNO_BOOST "
else
	LIBS+='-lboost_regex'
	CXXFLAGS+=" -DUSE_BOOST "
fi 

			#echo "-------------------------------------------------"
			#echo is_stream: $is_stream
			#echo p_opt: $p_opt
			#echo no_boost: $no_boost
			#echo snippet: $snippet
			#echo end_prt: $end_prt

${CXX-g++} $CXXFLAGS $prg.cc -o $prg $LIBS && $prg "$@"

# vim:set ts=8 sw=8 syntax=sh:   
